# Generated by Django 2.2.1 on 2019-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=20, verbose_name='Brand')),
                ('description', models.CharField(blank=True, max_length=3000, verbose_name='Description')),
                ('image_url', models.CharField(blank=True, max_length=3000, verbose_name='Image URL')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
